datasets=3, 6, 9, 12, 15, 18, 21, 24, 27

inputDir=C:/Users/Administrator/OneDrive - WU Wien/Desktop/emr/mapped/subsets/
outputDir=Z:/PhD/GUCONT-Obl/owl/evaluation/generated/

admissionsPerPatient=3

start=2024-01-01T00:00:00
end=2025-01-01T00:00:00

seed=42




